const constants = {
	ADD_TASK: "ADD_TASK",
	REMOVE_TASK: "REMOVE_TASK",
	EDIT_TASK: "EDIT_TASK",
	LIST_TASK: "LIST_TASK",
	COMPLETE_TASK: "COMPLETE_TASK",
	SET_STATUS: "SET_STATUS"

}

export default constants